import Table from "./components/table/Table";

function App() {
  const originalData = [
    {
      uname: " P37101724",
      repid: 21,
      roletechid: { a: 1 },
      name: "Viz Data",
      business_group: "Analytics Internal",
      business_sub_group: "Applications",
      zlob_name: "Retail",
      zdomainname: false,
      module_name: "Internal",
      portal_group: "",
      objecttechid: "https://rta.ril.com/dataapi-manager/#/dataset",
      zloadtimestamp: "20240403111849",
      objtype: "UI",
      moduleid: "TBI",
      trackid: "TIN",
      sourcesyst: "",
      rep_type: "",
      publishedfr: "1",
      rep_status: "1",
      bo_inst: "",
      objtype_name: "UI Application",
      sourcesyst_name: "",
      rep_status_name: "Published",
      bo_inst_name: "",
      rep_type_name: "",
      track_name: "Analytics Internal - Retail",
      lob: "RET",
      zpurpose: "Viz Data",
      zappname: '[{"AUTH_OBJECT":"STORE_NO","NAME":"Store","PARAMETER":"S1"}]',
      business_sub_group2: "",
      business_sub_group3: "",
      param1: "",
      param2: "",
      param3: "",
      zdomain: "RETTRT",
      zsubdomain: "RIN",
      rep_sortvalue: "",
      chngd_on: "20240311",
      chngd_at: "173645",
      last_chngd_on: "20240327",
      last_chngd_at: "152437",
      last_chngd_by: "JAYENDRA",
      citrix_only: "0",
      last_usage_date: "",
      yh_ts: "20240403054827",
    },
    {
      uname: " P37101724",
      repid: "T00025",
      roletechid: "ZHD_ANR_TBI_0002",
      name: "Launchpad User Details",
      business_group: "Analytics Internal",
      business_sub_group: "Applications",
      zlob_name: "Retail",
      zdomainname: true,
      module_name: "Internal",
      portal_group: "",
      objecttechid: "https://rta.ril.com/rtauserdetails",
      zloadtimestamp: "20240403111849",
      objtype: "UI",
      moduleid: "TBI",
      trackid: "TIN",
      sourcesyst: "",
      rep_type: "",
      publishedfr: "1",
      rep_status: "1",
      bo_inst: "",
      objtype_name: "UI Application",
      sourcesyst_name: "",
      rep_status_name: "Published",
      bo_inst_name: "",
      rep_type_name: "",
      track_name: "Analytics Internal - Retail",
      lob: "RET",
      zpurpose: "Launchpad User Details",
      zappname: '[{"AUTH_OBJECT":"STORE_NO","NAME":"Store","PARAMETER":"S1"}]',
      business_sub_group2: "",
      business_sub_group3: "",
      param1: "",
      param2: "",
      param3: "",
      zdomain: "RETTRT",
      zsubdomain: "RIN",
      rep_sortvalue: "",
      chngd_on: "20240319",
      chngd_at: "215210",
      last_chngd_on: "20240327",
      last_chngd_at: "152437",
      last_chngd_by: "JAYENDRA",
      citrix_only: "0",
      last_usage_date: "",
      yh_ts: "20240403054827",
    },
    {
      uname: " P37101724",
      repid: "T00027",
      roletechid: "ZHD_ANR_TBI_0002",
      name: "Analyse",
      business_group: "Analytics Applications",
      business_sub_group: "Data Applications",
      zlob_name: "",
      zdomainname: "",
      module_name: "Internal",
      portal_group: "",
      objecttechid: "http://mercury.jio.com/rover/",
      zloadtimestamp: "20240403111849",
      objtype: "UI",
      moduleid: "TBI",
      trackid: "TIN",
      sourcesyst: "",
      rep_type: "",
      publishedfr: "1",
      rep_status: "1",
      bo_inst: "",
      objtype_name: "UI Application",
      sourcesyst_name: "",
      rep_status_name: "Published",
      bo_inst_name: "",
      rep_type_name: "",
      track_name: "Analytics Internal - Retail",
      lob: "ANA",
      zpurpose: "Analyse",
      zappname: "",
      business_sub_group2: "",
      business_sub_group3: "",
      param1: "",
      param2: "WORKBENCH",
      param3: "",
      zdomain: "RETHCM",
      zsubdomain: "RLC",
      rep_sortvalue: "",
      chngd_on: "20240327",
      chngd_at: "122825",
      last_chngd_on: "20240327",
      last_chngd_at: "152437",
      last_chngd_by: "JAYENDRA",
      citrix_only: "0",
      last_usage_date: "",
      yh_ts: "20240403054827",
    },
    {
      uname: " P37101724",
      repid: "T00028",
      roletechid: "ZHD_ANR_TBI_0002",
      name: "Model",
      business_group: "Analytics Applications",
      business_sub_group: "Data Applications",
      zlob_name: "",
      zdomainname: "",
      module_name: "Internal",
      portal_group: "",
      objecttechid: "http://mercury.jio.com/rover/",
      zloadtimestamp: "20240403111849",
      objtype: "UI",
      moduleid: "TBI",
      trackid: "TIN",
      sourcesyst: "",
      rep_type: "",
      publishedfr: "1",
      rep_status: "1",
      bo_inst: "",
      objtype_name: "UI Application",
      sourcesyst_name: "",
      rep_status_name: "Published",
      bo_inst_name: "",
      rep_type_name: "",
      track_name: "Analytics Internal - Retail",
      lob: "ANA",
      zpurpose: "Model",
      zappname: "",
      business_sub_group2: "",
      business_sub_group3: "",
      param1: "",
      param2: "WORKBENCH",
      param3: "",
      zdomain: "ANABIN",
      zsubdomain: "RIN",
      rep_sortvalue: "",
      chngd_on: "20240327",
      chngd_at: "122825",
      last_chngd_on: "20240327",
      last_chngd_at: "152437",
      last_chngd_by: "JAYENDRA",
      citrix_only: "0",
      last_usage_date: "",
      yh_ts: "20240403054827",
    },
    {
      uname: " P37101724",
      repid: "T00029",
      roletechid: "ZHD_ANR_TBI_0002",
      name: "Find",
      business_group: "Analytics Applications",
      business_sub_group: "Data Applications",
      zlob_name: "",
      zdomainname: "",
      module_name: "Internal",
      portal_group: "",
      objecttechid: "http://mercury.jio.com/rover/",
      zloadtimestamp: "20240403111849",
      objtype: "UI",
      moduleid: "TBI",
      trackid: "TIN",
      sourcesyst: "",
      rep_type: "",
      publishedfr: "1",
      rep_status: "1",
      bo_inst: "",
      objtype_name: "UI Application",
      sourcesyst_name: "",
      rep_status_name: "Published",
      bo_inst_name: "",
      rep_type_name: "",
      track_name: "Analytics Internal - Retail",
      lob: "ANA",
      zpurpose: "Find",
      zappname: "",
      business_sub_group2: "",
      business_sub_group3: "",
      param1: "",
      param2: "WORKBENCH",
      param3: "",
      zdomain: "ANABIN",
      zsubdomain: "RIN",
      rep_sortvalue: "",
      chngd_on: "20240327",
      chngd_at: "122825",
      last_chngd_on: "20240327",
      last_chngd_at: "152437",
      last_chngd_by: "JAYENDRA",
      citrix_only: "0",
      last_usage_date: "",
      yh_ts: "20240403054827",
    },
    {
      uname: " P37101724",
      repid: "T00031",
      roletechid: "ZHD_ANR_TBI_0002",
      name: "Notebook AICOE (V72)",
      business_group: "Analytics Applications",
      business_sub_group: "Data Applications",
      zlob_name: "Retail",
      zdomainname: "",
      module_name: "Internal",
      portal_group: "",
      objecttechid: "",
      zloadtimestamp: "20240403111849",
      objtype: "UI",
      moduleid: "TBI",
      trackid: "TIN",
      sourcesyst: "",
      rep_type: "",
      publishedfr: "1",
      rep_status: "1",
      bo_inst: "",
      objtype_name: "UI Application",
      sourcesyst_name: "",
      rep_status_name: "Published",
      bo_inst_name: "",
      rep_type_name: "",
      track_name: "Analytics Internal - Retail",
      lob: "RET",
      zpurpose: "Notebook AICOE (V72)",
      zappname: "",
      business_sub_group2: "",
      business_sub_group3: "",
      param1: "",
      param2: "DATAPRODUCT",
      param3: "",
      zdomain: "RETHCM",
      zsubdomain: "RLC",
      rep_sortvalue: "",
      chngd_on: "20240327",
      chngd_at: "122825",
      last_chngd_on: "20240327",
      last_chngd_at: "152437",
      last_chngd_by: "JAYENDRA",
      citrix_only: "0",
      last_usage_date: "",
      yh_ts: "20240403054827",
    },
    {
      uname: "55054845",
      repid: "T00019",
      roletechid: "ZHD_ANR_TST_0001",
      name: "Store Manager Dashboard",
      business_group: "Geography Operations",
      business_sub_group: "Store",
      zlob_name: "Retail",
      zdomainname: "",
      module_name: "Internal",
      portal_group: "",
      objecttechid:
        "https://tab.jio.com/#/site/rta/views/StoreManagerDashboard/StoreManagerDashboard?:iid=1",
      zloadtimestamp: "20240403111849",
      objtype: "UI",
      moduleid: "TBI",
      trackid: "TIN",
      sourcesyst: "",
      rep_type: "",
      publishedfr: "1",
      rep_status: "1",
      bo_inst: "",
      objtype_name: "UI Application",
      sourcesyst_name: "",
      rep_status_name: "Published",
      bo_inst_name: "",
      rep_type_name: "",
      track_name: "Analytics Internal - Retail",
      lob: "RET",
      zpurpose: "Store Manager Dashboard",
      zappname: '[{"AUTH_OBJECT":"STORE_NO","NAME":"Store","PARAMETER":"S1"}]',
      business_sub_group2: "",
      business_sub_group3: "",
      param1: "",
      param2: "",
      param3: "",
      zdomain: "RETTRT",
      zsubdomain: "RIN",
      rep_sortvalue: "",
      chngd_on: "20240216",
      chngd_at: "174838",
      last_chngd_on: "20240327",
      last_chngd_at: "152437",
      last_chngd_by: "JAYENDRA",
      citrix_only: "0",
      last_usage_date: "",
      yh_ts: "20240403054827",
    },
    {
      uname: "55054845",
      repid: "T00020",
      roletechid: "ZHD_ANR_TST_0001",
      name: "UAT - Store Manager Dashboard - Tableau",
      business_group: "Geography Operations",
      business_sub_group: "Store",
      zlob_name: "Retail",
      zdomainname: "",
      module_name: "Internal",
      portal_group: "",
      objecttechid:
        "https://tab.jio.com/#/site/rta/views/StoreManagerDashboard/StoreManagerDashboard?:iid=1",
      zloadtimestamp: "20240403111849",
      objtype: "SC",
      moduleid: "TST",
      trackid: "TIN",
      sourcesyst: "",
      rep_type: "",
      publishedfr: "1",
      rep_status: "1",
      bo_inst: "",
      objtype_name: "SCORE CARD",
      sourcesyst_name: "",
      rep_status_name: "Published",
      bo_inst_name: "",
      rep_type_name: "",
      track_name: "Analytics Internal - Retail",
      lob: "RET",
      zpurpose: "Store Manager Dashboard",
      zappname: "NJ",
      business_sub_group2: "",
      business_sub_group3: "",
      param1: "",
      param2: "",
      param3: "",
      zdomain: "RETTRT",
      zsubdomain: "RIN",
      rep_sortvalue: "",
      chngd_on: "20240221",
      chngd_at: "170209",
      last_chngd_on: "20240221",
      last_chngd_at: "170209",
      last_chngd_by: "JAYENDRA",
      citrix_only: "0",
      last_usage_date: "",
      yh_ts: "20240403054827",
    },
    {
      uname: "AAAUSER",
      repid: "T00021",
      roletechid: "ZHD_ANR_TBI_0002",
      name: "Viz Data",
      business_group: "Analytics Internal",
      business_sub_group: "Applications",
      zlob_name: "Retail",
      zdomainname: "",
      module_name: "Internal",
      portal_group: "",
      objecttechid: "https://rta.ril.com/dataapi-manager/#/dataset",
      zloadtimestamp: "20240403111849",
      objtype: "UI",
      moduleid: "TBI",
      trackid: "TIN",
      sourcesyst: "",
      rep_type: "",
      publishedfr: "1",
      rep_status: "1",
      bo_inst: "",
      objtype_name: "UI Application",
      sourcesyst_name: "",
      rep_status_name: "Published",
      bo_inst_name: "",
      rep_type_name: "",
      track_name: "Analytics Internal - Retail",
      lob: "RET",
      zpurpose: "Viz Data",
      zappname: '[{"AUTH_OBJECT":"STORE_NO","NAME":"Store","PARAMETER":"S1"}]',
      business_sub_group2: "",
      business_sub_group3: "",
      param1: "",
      param2: "",
      param3: "",
      zdomain: "RETTRT",
      zsubdomain: "RIN",
      rep_sortvalue: "",
      chngd_on: "20240311",
      chngd_at: "173645",
      last_chngd_on: "20240327",
      last_chngd_at: "152437",
      last_chngd_by: "JAYENDRA",
      citrix_only: "0",
      last_usage_date: "",
      yh_ts: "20240403054827",
    },
    {
      uname: "AAAUSER",
      repid: "T00025",
      roletechid: "ZHD_ANR_TBI_0002",
      name: "Launchpad User Details",
      business_group: "Analytics Internal",
      business_sub_group: "Applications",
      zlob_name: "Retail",
      zdomainname: "",
      module_name: "Internal",
      portal_group: "",
      objecttechid: "https://rta.ril.com/rtauserdetails",
      zloadtimestamp: "20240403111849",
      objtype: "UI",
      moduleid: "TBI",
      trackid: "TIN",
      sourcesyst: "",
      rep_type: "",
      publishedfr: "1",
      rep_status: "1",
      bo_inst: "",
      objtype_name: "UI Application",
      sourcesyst_name: "",
      rep_status_name: "Published",
      bo_inst_name: "",
      rep_type_name: "",
      track_name: "Analytics Internal - Retail",
      lob: "RET",
      zpurpose: "Launchpad User Details",
      zappname: '[{"AUTH_OBJECT":"STORE_NO","NAME":"Store","PARAMETER":"S1"}]',
      business_sub_group2: "",
      business_sub_group3: "",
      param1: "",
      param2: "",
      param3: "",
      zdomain: "RETTRT",
      zsubdomain: "RIN",
      rep_sortvalue: "",
      chngd_on: "20240319",
      chngd_at: "215210",
      last_chngd_on: "20240327",
      last_chngd_at: "152437",
      last_chngd_by: "JAYENDRA",
      citrix_only: "0",
      last_usage_date: "",
      yh_ts: "20240403054827",
    },
  ];
  const tableContainerWidth = 95;
  return (
    <Table
      originalData={originalData}
      tableContainerWidth={tableContainerWidth}
    />
  );
}

export default App;
